config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'tests#index'

  resource :feedback, controller: :feedback, only: %i[show create]

  namespace :admin do
    resources :gists, only: %i[index]
    resources :tests, except: %i[edit] do
      member do
        post 'publish'
        post 'unpublish'
      end
      resources :questions, except: %i[index], shallow: true do
        resources :answers, except: %i[index show]
      end
    end
  end

  resources :tests, only: %i[index], defaults: { order: 'title_asc' } do
    member do 
      post :start
      post :continue
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  translates :body, fallbacks_for_empty_translations: true

  MAX_ANSWERS_COUNT = 4

  belongs_to :question

  validate :check_for_added_to_question, on: :create
  validates :body, presence: true

  scope :correct, -> { where(correct: true) }

  private

  def check_for_added_to_question
    errors.add(:overflow_answers, "Test can take only #{MAX_ANSWERS_COUNT} answers") if can_not_be_added_to_question?
  end

  def can_not_be_added_to_question?
    MAX_ANSWERS_COUNT < question.answers.size
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::AdminController
  before_action :set_answer, only: %i[edit update destroy]
  before_action :set_question, only: %i[new create]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to edit_admin_question_path(@question)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @answer.update(answer_params)
      redirect_to edit_admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    redirect_to edit_admin_question_path(@answer.question) if @answer.destroy
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
  def answer_form_heading(answer)
    answer.persisted? ? "Edit Answer" : "Create New Answer"
  end
end

app/views/admin/answers/_answer.html.erb
<li class="answer card">
  <div class="card-content">
    <div class="subtitle"><%= answer.body %></div>
    <div>
      <%= link_to t('crud.edit'), edit_admin_answer_path(answer), class: 'button is-link' %>
      <%= link_to t('crud.destroy'), admin_answer_path(answer), method: :delete, :data => {:confirm => 'Вы уверены?'}, class: 'button is-link' %>
    </div>
  </div>
</li>

app/views/admin/answers/_form.html.erb
<%= form_heading(answer) %>
<%= form_with model: [:admin, answer], url: url, class: 'form', local: true do |form| %>
  <div class="field">
    <%= form.label :body, class: 'label' %>
    <div class="control">
      <%= form.text_field :body, class: 'input' %>
      <%= form_error_field_prompt(answer, :body) %>
    </div>
  </div>
  <div class="field">
    <div class="control is-flex">
      <%= form.check_box :correct, class: 'checkbox' %>
      <%= form.label :correct, class: 'label' %>
    </div>
    <%= form_error_field_prompt(answer, :correct) %>
  </div>
  <div class="field">
    <div class="control">
      <%= form.submit class: 'button is-link' %>
    </div>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<%= render 'form', answer: @answer, url:  admin_answer_path(@answer) %>

app/views/admin/answers/new.html.erb
<%= render 'form', answer: @answer, url: admin_question_answers_path(@answer.question) %>