config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'tests#index'

  resource :feedback, controller: :feedback, only: %i[show create]

  namespace :admin do
    resources :gists, only: %i[index]
    resources :tests, except: %i[edit] do
      member do
        post 'publish'
        post 'unpublish'
      end
      resources :questions, except: %i[index], shallow: true do
        resources :answers, except: %i[index show]
      end
    end
  end

  resources :tests, only: %i[index], defaults: { order: 'title_asc' } do
    member do 
      post :start
      post :continue
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  translates :body, fallbacks_for_empty_translations: true

  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy

  validates :body, presence: true

  def serial_number
    test.questions.find_index(self) + 1
  end

  def last?
    serial_number == test.questions.order(id: :asc).size
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::AdminController
  before_action :set_test, only: %i[index create new]
  before_action :set_question, only: %i[edit show update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def new
    @question = @test.questions.build
  end

  def show; end

  def update
    if @question.update(question_params)
      redirect_to edit_admin_question_path(@question)
    else
      redirect_to :edit
    end
  end

  def create
    question = @test.questions.build(question_params)

    if question.save
      redirect_to admin_test_path(@test)
    else
      redirect_to new_admin_test_question_path(@test), alert: t('general_error')
    end
  end

  def destroy
    redirect_to admin_test_path(@question.test), notice: t('success') if @question.destroy
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def record_not_found
    render plain: t('network.404'), status: :not_found
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_test, only: %i[index create new]
  before_action :get_question, only: %i[edit show update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def new
    @question = @test.questions.build
  end

  def update
    if @question.update(question_params)
      redirect_to @question.test
    else
      redirect_to :edit
    end
  end

  def create
    question = @test.questions.build(question_params)

    if question.save
      redirect_to @test
    else
      redirect_to new_test_question_path(@test), alert: 'Упс, вопрос не был создан!'
    end
  end

  def destroy
    redirect_to @question.test if @question.destroy
  end

  private

  def get_test
    @test = Test.find(params[:test_id])
  end

  def get_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def record_not_found
    render plain: '404 Не найдено!', status: :not_found
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/questions/_form.html.erb
<div class="form">
  <%= form_heading(question) %>
  <%= form_with model: [:admin, test, question], url: url, class: 'form', local: true do |form| %>
    <div class="field">
      <%= form.label :body, class: 'label' %>
      <div class="control">
        <%= form.text_field :body, class: 'input' %>
        <%= form_error_field_prompt(question, :body) %>
      </div>
    </div>
    <div class="control">
      <%= form.submit class: 'button is-link' %>
    </div>
  <% end %>
</div>

app/views/admin/questions/_question.html.erb
<li class="question card">
  <div class="card-content">
    <div class="subtitle"><%= question.body %></div>
    <div class="is-grouped actions">
      <%= link_to t('crud.edit', model: ''), edit_admin_question_path(question), class: 'button is-link' %>
      <%= link_to t('crud.destroy', model: ''),  admin_question_path(question), method: :delete, :data => {:confirm => 'Вы уверены?'}, class: 'button is-link' %>
    </div>
  </div>
</li>

app/views/admin/questions/edit.html.erb
<div class="edit-question">
  <%= render 'form', test: @question.test, question: @question, url: admin_question_path(@question) %>
  <div class="answer-list">
    <div class="subtitle"><%= t('.answer_variants') %></div>
    <ul class="answers">
      <%= render @question.answers %>
    </ul>
  </div>
  <%= link_to t('.add_answer'), new_admin_question_answer_path(@question), class: 'button is-link' %>
</div>

app/views/admin/questions/new.html.erb
<div class="create_question">
  <%= render 'form', test: @test, question: @question, url: admin_test_questions_path(@test) %>
</div>