config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }

  root to: 'tests#index'

  resource :feedback, controller: :feedback, only: %i[show create]

  namespace :admin do
    resources :gists, only: %i[index]
    resources :tests, except: %i[edit] do
      member do
        post 'publish'
        post 'unpublish'
      end
      resources :questions, except: %i[index], shallow: true do
        resources :answers, except: %i[index show]
      end
    end
  end

  resources :tests, only: %i[index], defaults: { order: 'title_asc' } do
    member do 
      post :start
      post :continue
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def show; end

  def create
    email = params[:email]
    content = params[:content]
    UserMailer.with(email: email, content: content).feedback.deliver_now
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/show.html.erb
<%= form_with url: feedback_path, class: 'form' do |form| %>
  <div class="field">
    <%= form.label :email, t('.email'), class: 'label' %>
    <div class="control">
      <%= form.email_field :email, class: 'input' %>
    </div>
  </div>
  <div class="field">
    <%= form.label :content, t('.content'), class: 'label' %>
    <div class="control">
      <%= form.text_field :content, class: 'input' %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= form.submit t('.send'), class: 'button is-link' %>
    </div>
  </div>
<% end %>